import type { SkillGroup } from "@/types/content";

export const skillGroups: SkillGroup[] = [
  {
    label: "Languages",
    skills: ["TypeScript", "JavaScript", "SQL", "HTML", "CSS"],
  },
  {
    label: "Frontend",
    skills: [
      "React",
      "Next.js",
      "Angular",
      "Ionic",
      "React Native",
      "Tailwind CSS",
      "Material UI",
      "Redux",
      "MobX",
      "TanStack Query",
      "TanStack Router",
      "RxJS",
    ],
  },
  {
    label: "Backend & Data",
    skills: [
      "Node.js",
      "NestJS",
      "Express",
      "Django",
      "FastAPI",
      "GraphQL",
      "REST APIs",
      "WebSockets",
      "Socket.IO",
      "PostgreSQL",
      "MongoDB",
      "MySQL",
      "DynamoDB",
      "TypeORM",
      "Prisma",
      "Mongoose",
    ],
  },
  {
    label: "AI & LLM Engineering",
    skills: [
      "Anthropic Claude API",
      "OpenAI API",
      "Function/Tool Calling",
      "Structured Outputs",
      "Prompt Engineering",
      "RAG",
      "Embeddings",
      "Vector Search",
      "Hybrid Search",
      "MCP Servers & Clients",
      "Agentic Workflows",
      "Claude Code",
      "Developer Automation",
    ],
  },
  {
    label: "Cloud & Integrations",
    skills: [
      "AWS Lambda",
      "Cognito",
      "CloudWatch",
      "SES",
      "SNS",
      "CloudFront",
      "EC2",
      "RDS",
      "AWS SAM",
      "Docker",
      "GitHub Actions",
      "CI/CD",
      "Firebase",
      "Supabase",
      "Stripe",
      "Trust Commerce",
      "Celery",
      "JWT",
      "OneSignal",
      "Google Nest SDM APIs",
    ],
  },
];
